//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketManagementSystem.Resources.ValidationMessage", typeof(ValidationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кольору ID: {0} не існує..
        /// </summary>
        public static string ColorNotExists {
            get {
                return ResourceManager.GetString("ColorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номіналу ID: {0} не існує..
        /// </summary>
        public static string NominalNotExists {
            get {
                return ResourceManager.GetString("NominalNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пачка закрита..
        /// </summary>
        public static string PackageClosed {
            get {
                return ResourceManager.GetString("PackageClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неможливо встановити цифу {0}, оскільки пачка містить квитки з іншою..
        /// </summary>
        public static string PackageFirstDigitCannotBeSet {
            get {
                return ResourceManager.GetString("PackageFirstDigitCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перша цифра квитка не підтримується пачкою..
        /// </summary>
        public static string PackageFirstDigitDiffFromTicket {
            get {
                return ResourceManager.GetString("PackageFirstDigitDiffFromTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пачка з іменем &quot;{0}&quot; вже існує..
        /// </summary>
        public static string PackageNameExists {
            get {
                return ResourceManager.GetString("PackageNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номінал, колір або серія квитка не підтримуються пачкою..
        /// </summary>
        public static string PackageNomColSerDiffFromTicket {
            get {
                return ResourceManager.GetString("PackageNomColSerDiffFromTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пачки ID: {0} не існує..
        /// </summary>
        public static string PackageNotExists {
            get {
                return ResourceManager.GetString("PackageNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пачка відкрита..
        /// </summary>
        public static string PackageOpened {
            get {
                return ResourceManager.GetString("PackageOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неможливо встановити нові колір/серію/номінал, бо пачка містить квитки з іншими..
        /// </summary>
        public static string PackagePropertiesAreDifferent {
            get {
                return ResourceManager.GetString("PackagePropertiesAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серії ID: {0} не існує..
        /// </summary>
        public static string SerialNotExists {
            get {
                return ResourceManager.GetString("SerialNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квиток з таким номером вже існує..
        /// </summary>
        public static string TicketAlreadyExists {
            get {
                return ResourceManager.GetString("TicketAlreadyExists", resourceCulture);
            }
        }
    }
}
