using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Optimization;

namespace TicketManagementSystem.Web.App_Start.Bundles
{
    public static class ScriptBundles
    {
        public static void RegisterBundles(BundleCollection bundles)
        {
            Vue(bundles);
            Main(bundles);
            StatisticsEngine(bundles);
        }

        private static void Vue(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/vue/js").Include(
                "~/Scripts/lib/vue.min.js"));
        }

        private static void Main(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/main/js").Include(
                "~/Scripts/AutoGenerated/Common/service-base.js"));
        }

        private static void StatisticsEngine(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/statistics-engine/js").Include(
                "~/Scripts/AutoGenerated/StatisticsEngine/Models/*.js",
                "~/Scripts/AutoGenerated/StatisticsEngine/statistics-service.js",
                "~/Scripts/AutoGenerated/StatisticsEngine/statistics-business.js",
                "~/Scripts/AutoGenerated/StatisticsEngine/statistics-controller.js"));
        }
    }
}