// <auto-generated />
namespace TicketManagementSystem.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TodoTask_IncreasedFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TodoTask_IncreasedFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201707290817277_TodoTask_IncreasedFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
